{
 "title": "Scaling Alerts",
 "tags": [ "admins" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Diego Cells",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Diego Cells - Total Memory Available %",
     "type": "graph",
     "description": "Percentage of remaining memory capacity for a given cell.\n\nWhen to scale:\nTotal memory available should be greater than 10-20% otherwise scale up",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit", "label": "percentage available" }
     ],
     "targets": [
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "lva - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "lva - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "lva - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "lva - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "lvc - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "lvc - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "lvc - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "lvc - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "pxa - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "pxa - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "pxa - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "pxa - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "pxc - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "pxc - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "pxc - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "pxc - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "jca - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "jca - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "jca - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "jca - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "jcc - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_memory_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "jcc - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "jcc - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "jcc - windows cert"
      }
     ]
    },
    {
     "title": "Diego Cells - Total Disk Available %",
     "type": "graph",
     "description": "Percentage of remaining disk capacity for a given cell.\n\nWhen to scale:\nTotal disk available should be greater than 10-20% otherwise scale up",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "percentunit", "label": "percentage available" }
     ],
     "targets": [
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "lva - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "lva - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "lva - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "lva - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "lvc - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "lvc - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "lvc - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "lvc - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "pxa - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "pxa - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "pxa - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "pxa - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "pxc - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "pxc - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "pxc - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "pxc - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "jca - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "jca - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "jca - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "jca - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "jcc - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_disk_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "jcc - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "jcc - windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_disk{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "jcc - windows cert"
      }
     ]
    },
    {
     "title": "Diego Cells - Total Container Capacity Available %",
     "type": "graph",
     "description": "Percentage of remaining container capacity for a given cell (regards to the number of containers a cell can host)\n\nWhen to scale:\nTotal container capacity available should be greater than 10-20% otherwise scale up",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "percentunit", "label": "percentage available" }
     ],
     "targets": [
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "lva - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "lva - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "lva - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "lvc - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "lvc - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "lvc - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "pxa - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "pxa - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "pxa - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "pxc - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "pxc - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "pxc - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "jca - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "jca - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "jca - windows cert"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=\"cf\"}",
       "legendFormat": "jcc - cf"
      },
      {
       "expr": "firehose_value_metric_healthwatch_diego_total_percentage_available_container_capacity_5_m{bosh_deployment=~\"p-isolation-segment.*\"}",
       "legendFormat": "jcc - p-isolation-segment"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell\"})",
       "legendFormat": "windows"
      },
      {
       "expr": "avg(firehose_value_metric_rep_capacity_remaining_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})/avg(firehose_value_metric_rep_capacity_total_containers{bosh_job_name=\"windows_diego_cell_cert_wrt\"})",
       "legendFormat": "jcc - windows cert"
      }
     ]
    }
   ]
  },
  {
   "title": "Firehose",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Firehose - Total Doppler Ingress",
     "type": "graph",
     "description": "Total number of messages (envelopes) coming into the doppler servers",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none", "label": "(in thousands)" }
     ],
     "targets": [
      {
       "expr": "firehose_value_metric_healthwatch_ingestor_ingested",
       "legendFormat": "lva - Number of Messages Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_ingestor_ingested",
       "legendFormat": "lvc - Number of Messages Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_ingestor_ingested",
       "legendFormat": "pxa - Number of Messages Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_ingestor_ingested",
       "legendFormat": "pxc - Number of Messages Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_ingestor_ingested",
       "legendFormat": "jca - Number of Messages Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_ingestor_ingested",
       "legendFormat": "jcc - Number of Messages Per Min"
      }
     ]
    },
    {
     "title": "Firehose - Doppler Message Rate ",
     "type": "graph",
     "description": "Represents the average rate of envelopes (messages) per Doppler instance. \n\nWhen to scale:\nAverage load on the Doppler instances should be <16,000 envelopes per second, or 1 million envelopes per minute.  Scale up Doppler when this threshold is reached.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "per minute" }
     ],
     "targets": [
      {
       "expr": "firehose_value_metric_healthwatch_doppler_messages_average_1_m",
       "legendFormat": "lva - Avg Number of Doppler Messages"
      },
      {
       "expr": "firehose_value_metric_healthwatch_doppler_messages_average_1_m",
       "legendFormat": "lvc - Avg Number of Doppler Messages"
      },
      {
       "expr": "firehose_value_metric_healthwatch_doppler_messages_average_1_m",
       "legendFormat": "pxa - Avg Number of Doppler Messages"
      },
      {
       "expr": "firehose_value_metric_healthwatch_doppler_messages_average_1_m",
       "legendFormat": "pxc - Avg Number of Doppler Messages"
      },
      {
       "expr": "firehose_value_metric_healthwatch_doppler_messages_average_1_m",
       "legendFormat": "jca - Avg Number of Doppler Messages"
      },
      {
       "expr": "firehose_value_metric_healthwatch_doppler_messages_average_1_m",
       "legendFormat": "jcc - Avg Number of Doppler Messages"
      }
     ]
    },
    {
     "title": "Firehose - Slow Consumer Drops Delta",
     "type": "graph",
     "description": "Metrics and logs enter the Firehose for transport and exit out of the platform through a consumer nozzle. If the consuming downstream system fails to keep up with the exiting stream of metrics, the Firehose is forced to close the connection to protect itself from back-pressure. The Firehose increments slow_consumer with each connection that it closes because a consumer could not keep up. This represents the change in number of drops.\n\nWhen to scale:\nScale when the rate of Firehose Slow Consumer Drops is irregular for a given environment.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_slow_consumer_delta",
       "legendFormat": "lva - Firehose "
      },
      {
       "expr": "firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_slow_consumer_delta",
       "legendFormat": "lvc - Firehose "
      },
      {
       "expr": "firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_slow_consumer_delta",
       "legendFormat": "pxa - Firehose "
      },
      {
       "expr": "firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_slow_consumer_delta",
       "legendFormat": "pxc - Firehose "
      },
      {
       "expr": "firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_slow_consumer_delta",
       "legendFormat": "jca - Firehose "
      },
      {
       "expr": "firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_slow_consumer_delta",
       "legendFormat": "jcc - Firehose "
      }
     ]
    },
    {
     "title": "Firehose - Dropped Messages",
     "type": "graph",
     "description": "The loss rate occurring as messages are transported from the Loggregator Agent components through the Doppler components to the Firehose endpoints.\n\nWhen to scale:\nShould be less than 1%. Scale up the number of Traffic Controllers and Doppler instances when threshold is reached.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percent", "label": "percentage dropped" }
     ],
     "targets": [
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_m",
       "legendFormat": "lva - Firehose Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_h",
       "legendFormat": "lva - Firehose Loss Rate Per Hour"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_m",
       "legendFormat": "lvc - Firehose Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_h",
       "legendFormat": "lvc - Firehose Loss Rate Per Hour"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_m",
       "legendFormat": "pxa - Firehose Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_h",
       "legendFormat": "pxa - Firehose Loss Rate Per Hour"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_m",
       "legendFormat": "pxc - Firehose Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_h",
       "legendFormat": "pxc - Firehose Loss Rate Per Hour"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_m",
       "legendFormat": "jca - Firehose Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_h",
       "legendFormat": "jca - Firehose Loss Rate Per Hour"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_m",
       "legendFormat": "jcc - Firehose Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_firehose_loss_rate_1_h",
       "legendFormat": "jcc - Firehose Loss Rate Per Hour"
      }
     ]
    },
    {
     "title": "Firehose - Adatper Loss Rate",
     "type": "graph",
     "description": "The loss rate of the Syslog Adapters, that is, the total messages dropped as a percentage of the total traffic coming through the Syslog Adapters. Total messages include only logs for bound applications. \n\nWhen to scale:\nShould be less than 1% otherwise performance test your syslog server, review the logs of the syslog consuming system for intake and other performance issues that indicate a need to scale the consuming system. ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "percent", "label": "percentage dropped" }
     ],
     "targets": [
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_adapter_loss_rate_1_m",
       "legendFormat": "lva - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_adapter_loss_rate_1_m",
       "legendFormat": "lvc - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_adapter_loss_rate_1_m",
       "legendFormat": "pxa - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_adapter_loss_rate_1_m",
       "legendFormat": "pxc - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_adapter_loss_rate_1_m",
       "legendFormat": "jca - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_adapter_loss_rate_1_m",
       "legendFormat": "jcc - Firehose Syslog Loss Rate Per Min"
      }
     ]
    }
   ]
  },
  {
   "title": "Reverse Log Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reverse Log Proxy - Avg Subscriptions",
     "type": "graph",
     "description": "The Reverse Log Proxy (RLP) limits the number of subscriptions. A subscription is a consumer of the RLP so this metric concerns the number of concurrent consumer of an RLP instance. The maximum subscription count is 1000 per RLP.\n\nWhen to scale:\nWhen the number of subscriptions reaches or crosses, scale up the number of traffic controllers",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(firehose_value_metric_loggregator_doppler_subscriptions)",
       "legendFormat": "lva - Average Number of Subscriptions"
      },
      {
       "expr": "avg(firehose_value_metric_loggregator_doppler_subscriptions)",
       "legendFormat": "lvc - Average Number of Subscriptions"
      },
      {
       "expr": "avg(firehose_value_metric_loggregator_doppler_subscriptions)",
       "legendFormat": "pxa - Average Number of Subscriptions"
      },
      {
       "expr": "avg(firehose_value_metric_loggregator_doppler_subscriptions)",
       "legendFormat": "pxc - Average Number of Subscriptions"
      },
      {
       "expr": "avg(firehose_value_metric_loggregator_doppler_subscriptions)",
       "legendFormat": "jca - Average Number of Subscriptions"
      },
      {
       "expr": "avg(firehose_value_metric_loggregator_doppler_subscriptions)",
       "legendFormat": "jcc - Average Number of Subscriptions"
      }
     ]
    },
    {
     "title": "Reverse Log Proxy Loss Rate",
     "type": "graph",
     "description": "The loss rate of the reverse log proxies (RLP), that is, the total messages dropped as a percentage of the total traffic coming through the reverse log proxy. Total messages include only logs for bound applications. \n\nWhen to scale:\nShould be less than 1%. Scale up the number of traffic controllers when this threshold is reached",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "percent", "label": "percentage dropped" }
     ],
     "targets": [
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_rlp_loss_rate_1_m",
       "legendFormat": "lva - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_rlp_loss_rate_1_m",
       "legendFormat": "lvc - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_rlp_loss_rate_1_m",
       "legendFormat": "pxa - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_rlp_loss_rate_1_m",
       "legendFormat": "pxc - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_rlp_loss_rate_1_m",
       "legendFormat": "jca - Firehose Syslog Loss Rate Per Min"
      },
      {
       "expr": "firehose_value_metric_healthwatch_syslog_drain_rlp_loss_rate_1_m",
       "legendFormat": "jcc - Firehose Syslog Loss Rate Per Min"
      }
     ]
    }
   ]
  },
  {
   "title": "Routers and UAA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Routing - VM CPU Utilization",
     "type": "graph",
     "description": "CPU utilization for each Gorouter\n\nWhen to scale:\nCPU usage should be within a maximum range of 60-70% for the best Gorouter performance. \n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percent", "label": "cpu (user) usage" }
     ],
     "targets": [
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"router\"}",
       "legendFormat": "lva - Router VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"router\"}",
       "legendFormat": "lvc - Router VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"router\"}",
       "legendFormat": "pxa - Router VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"router\"}",
       "legendFormat": "pxc - Router VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"router\"}",
       "legendFormat": "jca - Router VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"router\"}",
       "legendFormat": "jcc - Router VM"
      }
     ]
    },
    {
     "title": "UAA - VM CPU Utilization",
     "type": "graph",
     "description": "CPU utilization for each UAA vm\n\nWhen to scale:\nCPU usage should be within a maximum range of 80-90% for the best UAA performance. . ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "percent", "label": "cpu (user) usage" }
     ],
     "targets": [
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"uaa\"}",
       "legendFormat": "lva - UAA VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"uaa\"}",
       "legendFormat": "lvc - UAA VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"uaa\"}",
       "legendFormat": "pxa - UAA VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"uaa\"}",
       "legendFormat": "pxc - UAA VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"uaa\"}",
       "legendFormat": "jca - UAA VM"
      },
      {
       "expr": "bosh_job_cpu_user{bosh_deployment=~\"cf.*\",bosh_job_name=\"uaa\"}",
       "legendFormat": "jcc - UAA VM"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS - Persistent Disk Usage %",
     "type": "graph",
     "description": "PAS internal NFS Server persistent disk usage \n\nWhen to scale:\nTotal usage should be below 75%",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "percent", "label": "percent used" }
     ],
     "targets": [
      {
       "expr": "bosh_job_persistent_disk_percent{bosh_deployment=~\"cf.*\",bosh_job_name=\"nfs_server\"}",
       "legendFormat": "lva - Disk Usage"
      },
      {
       "expr": "bosh_job_persistent_disk_percent{bosh_deployment=~\"cf.*\",bosh_job_name=\"nfs_server\"}",
       "legendFormat": "lvc - Disk Usage"
      },
      {
       "expr": "bosh_job_persistent_disk_percent{bosh_deployment=~\"cf.*\",bosh_job_name=\"nfs_server\"}",
       "legendFormat": "pxa - Disk Usage"
      },
      {
       "expr": "bosh_job_persistent_disk_percent{bosh_deployment=~\"cf.*\",bosh_job_name=\"nfs_server\"}",
       "legendFormat": "pxc - Disk Usage"
      },
      {
       "expr": "bosh_job_persistent_disk_percent{bosh_deployment=~\"cf.*\",bosh_job_name=\"nfs_server\"}",
       "legendFormat": "jca - Disk Usage"
      },
      {
       "expr": "bosh_job_persistent_disk_percent{bosh_deployment=~\"cf.*\",bosh_job_name=\"nfs_server\"}",
       "legendFormat": "jcc - Disk Usage"
      }
     ]
    }
   ]
  }
 ]
}