---
name: gogs

instance_groups:
- name: gogs
  azs: ((azs))
  instances: 1
  vm_type: large
  stemcell: default
  persistent_disk: 10_240
  networks: [{name: default}]
  jobs:
  - name: postgres
    release: gogs
  - name: gogs
    release: gogs
    properties:
      authentication: |+
        - type:
            name: LDAP
            id: 101
            type: ldap_bind_dn
            is_activated: true
            is_default: true
          config:
            host: ((ldap_host))
            port: 389
            security_protocol: 0
            skip_verify: true
            bind_dn: ((ldap_bind_dn))
            bind_password: ((ldap_user_pass))
            user_base: ((ldap_user_search_base_dn))
            attribute_username: uid
            attribute_name: givenName
            attribute_surname: sn
            attribute_mail: mail
            attributes_in_bind:
            filter: (&(objectClass=inetOrgPerson)(|(uid=%s)(mail=%s)))
            admin_filter:
            group_enabled: false
            group_dn:
            group_filter:
            group_member_uid:
            user_uid:
      gogs:
        admin: ((gogs_user.username))
        password: ((gogs_user.password))
        email: "pcfadmins@xyz.com"
        port: 8080
        tls_cert: ((gogs-tls.certificate))
        tls_key: ((gogs-tls.private_key))
        secret_key: ((gogs-secret-key))
        domain: gogs.((system_domain))
      databases:
        roles:
          - tag: gogs
            name: gogs
            password: ((postgres-password))
        databases:
          - tag: gogs
            name: gogsdb
            citext: true

- name: sanity-test
  azs: ((azs))
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanity_test
    release: gogs
    properties:
      gogs:
        admin: ((gogs_user.username))
        password: ((gogs_user.password))
        domain: gogs.((system_domain))



variables:
- name: postgres-password
  type: password
- name: gogs-secret-key
  type: password
- name: gogs_user
  options:
    username: gogs
  type: user
- name: gogs-ca
  type: certificate
  options:
    is_ca: true
    duration: 3650
    common_name: gogsCA
- name: gogs-tls
  type: certificate
  options:
    ca: gogs-ca
    common_name: gogs
    duration: 1825
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
    - "*.gogs.default.gogs.bosh"

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: gogs
  version: latest