# Apply ./bosh/add-bosh-exporter-uaa-clients.yml to your bosh-deployment
# Taken from https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/enable-bosh-uaa.yml
# bosh_ca_cert var cahnged
# Use bosh_exporter UAA client
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=bosh_exporter/properties/bosh_exporter/bosh
  value:
    url: "((internal_ip))"
    uaa:
      client_id: bosh_exporter
      client_secret: "((uaa_bosh_exporter_client_secret))"
    ca_cert: "((/certs/wildcard.ca))"