# Apply ./bosh/add-credhub-exporter-uaa-clients.yml to your bosh-deployment
# Taken from https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/monitor-credhub.yml
# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: credhub_exporter
    release: prometheus
    properties:
      credhub_exporter:
        credhub:
          api_url: "((internal_ip)):8844"
          client_id: credhub_exporter
          client_secret: "((uaa_credhub_exporter_client_secret))"
          ca_certs: "((credhub_tls.certificate)"
        metrics:
          deployment: credhub
          environment: "((director_name))"
        skip_ssl_validation: ((skip_ssl_validation))
        filters:
          generic-certificates:
            - "/static/.*"

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=credhub_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/credhub_alerts/*.alerts.yml